GET http://localhost:8080/books/
###
GET http://localhost:8080/authors/
###
POST http://localhost:8080/books HTTP/1.1
Content-Type: application/json

{
    "title": "Harry Potter and the Philosophers Stone",
    "format": "req.body.format",
    "publication": "req.body.publication",
    "pages": "five",
    "author": "req.body.author",
    "genre": "req.body.genre",
    "description": "req.body.description"
}
###
POST http://localhost:8080/authors HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jk",
    "lastName": "Rowling",
    "birthDate": "7/22/2003",
    "deathDate":"",
    "bio": "req.body.bio"
}
###
PUT http://localhost:8080/authors/646d280dd8aae467b569f5e1 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jk",
    "lastName": "Rowling",
    "birthDate": "",
    "deathDate":"8/16/2050",
    "bio": "req.body.bio"
}
###
GET https://cse341-books.onrender.com/books/
###
GET https://cse341-books.onrender.com/authors/